### ISSUE TITLE
RWT missing

### ISSUE THREAD

**Issue by asraghu123** [waywardcoder/NinjaIndicators#1]
Hi Richard,

    When I compile the indicators, looks like the RWT.xxxxxx   reference is not resolved.  I think something is missing/dependencies. 
    Can you check.  

Regards,
asraghu

**Comment by rwtodd** [comment]
You are talking about code for an old version of ninjatrader from more than 8 years ago.  If you can tell me a specific indicator you are trying to compile, I will look at the code and try to spot your issue, but I'm not running any of these anymore so that's all I can do.

**Comment by asraghu123** [comment]
Hi Richard.  Nice to hear from you. I used to be regular at your MtM blog and at Prospectus blog in 2008/2009. You are an **excellent coder** as I knew you on your work for EOTPRO.   Coming to the issue,  I am using NT7  and I happened to hit your recent years folder in the code archive.  When I compile your indicators in NT7, I get an error that says
Indicator ZCBL  from   Ninja7.Indicators_Pre2012-master\recent_years

private System.Windows.Forms.ToolStrip strip = null;
		private RWT.ZControlHost tsch = null;
		private System.Windows.Forms.TrackBar tbar = null;


![image](https://user-images.githubusercontent.com/76263329/103694672-f7561280-4f60-11eb-9847-940bad620a3e.png)

Error is   indicator\zCBL.cs :  The type or namespace RWT could not be found.  ......

Is RWT a DLL library that is missing in the archive ?'

Regards,
asraghu

**Comment by rwtodd** [comment]
I think you need to add and compile zFader.cs from that same recent years directory first.  Some of those indicators supported a fader so you could make all the lines transparent or opaque with a fader in the chart window's toolbar.  To do that, they talk to the zFader indicator (i think!  It's been a while).

There are some custom bar-type (the ones with "Rich" in the name, I think) that do need a DLL, which is possible to build and install, but I don't have a pre-built one anymore.  But the ones that want RWT.fader stuff should work ok without any dlls.  Let me know how it goes.

**Comment by asraghu123** [comment]
Hi Rich,

  Thanks for the clue, it did help compile a number of indicators.  I still
need some clue on the following two issue. One is related to office lib and
another RWT_MA reference.  see attached word file

Regards,

**Comment by rwtodd** [comment]
Sorry I don't see an attachment, but RWT_MA stuff is in zMovingAverage, so compile that file first and anything that depends on it will be ok.  I did have some stuff that would push journal entries into a word document also, and I think to make that work you have to "add a reference" to the office interop libraries from ninja (it's in the menus somewhere) before it will work.  Although it would not surprise me if some of that code needed updates because there have been many versions of MS Office since 2012.

**Comment by asraghu123** [comment]
Hi Richard,   

   RWT_MA reference issue is resolved. I am searching for the interop lib DLLs and have figured out the place in Ninja to add them.  Thanks a lot, Now I need to understand the indicators and learn their behavior.   Thanks for your efforts in 2008-2012 in refining and implementing some unique ideas. 

Regards

**Comment by rwtodd** [comment]
I hope you find some useful stuff in there!  I liked the RWT_MA idea a lot, I wish ninja worked that way, so you could just choose which kind of smoothing to use inside of all the other indicators.

I'm pretty sure it was just one indicator for journaling that used the Office interop, so it would be no big loss if you never worked that out.  I had this setup where I'd add markers to the chart, with explanations, and then I could press a button and push the chart with the annotations into a Word document.  Just to save some effort when journalling the day.

**Comment by asraghu123** [comment]
Hi Richard,

     Thanks, I will plot all the indicators soon in Ninja 7 and see how
useful they can be in trading.
     If I can ask, Are you using aunty indicators for trading now or have
figured out a different way to trade. Just curious.  What setups work ? I
am using Order flow (volume ladder) and for confirmation renko charts with
some of your indicators.
     I knew you lived in Dallas in 2009. I too live in Dallas/Coppell area.
we should meet sometime.   I am following your tweeter, lets connect via
message there or you can email me at alankar.raghu@gmail.com

Regards,
Raghu

**Comment by asraghu123** [comment]
Corrected.   Aunty mistype for Any
